## Sets : 
1. sets do not allow duplicates
2. sets have no indexing or slicing
3. sets dont allow mutable data types
4. sets itself a mutable data type

In [17]:
# Creating a set : 

# empty set : 
s={} # it wont be an empty set
print(type(s))
# to create empty set : 
s=set()
print(type(s))

s={1,2,3,4,5} # homogeneous
s2={12,3,4,"hello"} # hetrogeneous

s={1,2,33,33,5,9,55} # duplicates will be removed
print(s)

# sets do not allow mutable data types : 
# s={1,2,3,[1,2,3]} # error as lists are mutabele

s={1,2,3,(1,2,3)} # this will work , as tuples are not mutable

s={(1,2,3),"Hello"} # sets do not have any indexing 
print(s) # why hello came first -> because of hashing

# 2d set is not possible : 

# s={1,2,3,{4,5}} -> because set itself is mutable so it

<class 'dict'>
<class 'set'>
{1, 2, 33, 5, 55, 9}
{'Hello', (1, 2, 3)}

In [23]:
# Accessing Items : 

# editing not possible in set : 
s={1,2,3,4,5,6}
# s[0] -> not possible as sets do not follow indexing 


# add items : 
s.add(77)
print(s)

{1, 2, 3, 4, 5, 6, 77}

In [30]:
# Deleting Items : 

s={1,2,3,4}
# delete whole set : 
del s
# print (s) 

# remove : 
s={1,2,3,4,999,4,3}
s.remove(999)
print(s)

# pop : 
print(s.pop())
print(s)

{1, 2, 3, 4}
1
{2, 3, 4}

In [34]:
# Set Operations : 

# ARITHMATIC AND MULTIPLICATION OPERATORS DONT WORK 

# loop : 
s={1,2,3,4,5,65}
for i in s:
    print(i,end=' ')

print()

# membership :
print(65 in s)

1 2 3 4 5 65
True

In [36]:
# Functions : 
s={1,2,3,4,5,6,7}

print(len(s))
print(min(s))
print(max(s))
print(sum(s))
print(sorted(s))
print(sorted(s,reverse=True))

7
1
7
28
[1, 2, 3, 4, 5, 6, 7]
[7, 6, 5, 4, 3, 2, 1]

In [41]:
# Functions only for sets : 

s1={1,2,3,4}
s2={5,6,1,7,8}

print(s1.union(s2))

print(s1.intersection(s2))

print(s1.difference(s2))

print(s1.symmetric_difference(s2))

print(s1.isdisjoint(s2))

print(s1.issuperset(s2))

{1, 2, 3, 4, 5, 6, 7, 8}
{1}
{2, 3, 4}
{2, 3, 4, 5, 6, 7, 8}
False
False